# PLAN:
#   1. USER INPUTS DATA  (TREAT AS AN OBJECT - MAKE DICTIONARY)
#          - CHOICE: INCOME OR EXPENSE
#          - CHOOSE EXPENSE TYPE
#          - DISPLAYS CALCULATOR () TO ENTER THE AMOUNT
#          - CHOICE IF HE'LL ENTER NOTE
#          - PARSE IF A BUTTON IS PRESSED
#   2. STORE DATA IN FILE
#           - OBJECT WILL BE STORED IN THE FILE
#   3. ACCESS DATA FROM THE FILE
#           - READ THE FILE TO SEE THE DATA
#   4. DISPLAY THE LIST OF INCOME AND EXPENSES AND THE OTHER DATA PER DAY
#   5. MAKE AN ALGORITHM THAT WILL COMPUTE FOR THE REMAINING BALANCE EVERYTIME THE USER INPUTS INCOME OR EXPENSE (PER DAY/ PER MONTH) [aira]
#
#
#
